### PR TITLE
Add Schedutalk to list of projects

### PR DESCRIPTION
**Pull request by codewitchio**
Not exactly certain what to write for our project, but uncertainty is better than nothing right?

### CODE REVIEW

**Comment by macaullyjames** [comment]
Haha, yes ^^

**Comment by macaullyjames** [comment]
I'm rejecting this because you screwed up the Git blame though (see the diff). `git diff` is your friend! 😉

**Comment by codewitchio** [comment]
So how do I prevent that from happening? I never touched @mictab's line except for clicking it once just to create a new line underneath it :sob: Tried it again with the same result :disappointed:

**Comment by macaullyjames** [comment]
Haha, funny story...

Apparently there was no newline at the end of @mictab's line. When you add your line beneath it adds a newline to the line above, which is why it looks like you've edited two lines instead of one. So... it's totally @mictab's fault.

I'd reopen and merge this but it looks like you've deleted the branch :(

**Comment by mictab** [comment]
Heheheheh.

**Pull request closed without merging**
